server:
  port: 8080
#spring:
#  security:
#    user:
      #自定义账号密码都为admin
#      name: admin
#     password: admin
spring:
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/Mybatis_plus?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl