CREATE DATABASE Mybatis_plus CHARACTER SET UTF8;

USE Mybatis_plus;

SHOW TABLES;
CREATE TABLE `user`(
`id` BIGINT(20) NOT NULL COMMENT '主键ID',
`name` VARCHAR(30) DEFAULT NULL COMMENT '姓名',
`age` INT(11) DEFAULT NULL COMMENT '年龄',
`email` VARCHAR(50) DEFAULT NULL COMMENT '邮箱',
PRIMARY KEY (`id`)

) ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE `user` ADD COLUMN `username` VARCHAR(50) NOT NULL COMMENT '用户名';
ALTER TABLE `user` MODIFY COLUMN `password` VARCHAR(200) NOT NULL COMMENT '密码';
ALTER TABLE `user` MODIFY COLUMN `id` BIGINT(20) NOT NULL AUTO_INCREMENT;


SELECT * FROM USER;

INSERT INTO USER(`name`,age,email,`password`,`username`) VALUE
 ('张三','12','1249595889@qq.com','123456','admin');

UPDATE USER SET PASSWORD = '123456' WHERE id = 1;

SELECT * FROM USER WHERE username ='admin1'

